# Generated by Django 4.2.1 on 2023-10-21 08:15

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=house.models.GenerateHouseImagePath()),
        ),
    ]
